mytitle8/mytitle8/urls.py
from django.conf.urls import url
from crm import views, ajax_views, head_teacher_views
from django.contrib import admin

urlpatterns = [
    url(r'^admin/$', admin.site.urls),
    url(r'^login/$', views.login),
    url(r'^reg/$', views.reg),
    url(r'^index/$', views.index),
    url(r'^customer_list/$', views.CustomerListView.as_view()),  # 所有客户列表
    url(r'^my_customer/$', views.CustomerListView.as_view()),  # 我的客户列表
    url(r'^reg2/$', views.RegView.as_view()),
    # url(r'^add/', views.add_customer),
    # url(r'^edit/(\d+)/$', views.edit_customer),

    # ----------------把add跟edit放在一个视图函数里------------
    url(r'^add/$', views.customer),
    url(r'^edit/(\d+)/$', views.customer),

    # --------------------沟通记录表-------------
    url(r'^consult_record/(?P<cid>\d+)/$', views.consult_record_list, name='consult_record'),
    url(r'^add_consult_record/$', views.consult_record),
    url(r'^edit_consult_record/(\d+)/$', views.consult_record),

    # ----------------------报名表-------------------
    url(r'^enrollment_list/(?P<customer_id>\d+)/$', views.EnrollmentListView.as_view(), name='enrollment_list'),
    # 查看报名记录
    url(r'^add_enrollment/(?P<customer_id>\d+)/$', views.enrollment),
    url(r'^edit_enrollment/(?P<enrollment_id>\d+)/$', views.enrollment),

    # AJAX提交
    url(r'^ajax_class/$', ajax_views.ajax_class),

    # 班级管理
    url(r'^class_list/$', head_teacher_views.ClassListView.as_view()),
    url(r'add_class/$', head_teacher_views.op_class),
    url(r'edit_class/$', head_teacher_views.op_class),

    # 课程记录
    # 因为查询课程记录 一定要指定查询某个班级的上课记录
    url(r'course_record_list/(?P<class_id>\d+)$', head_teacher_views.CourseListView.as_view(), name='course_record_list'),
    url(r'add_course_record/(?P<class_id>\d+)$', head_teacher_views.course_record, name='add_course_record'),
    url(r'edit_course_record/(?P<course_record_id>\d+)$', head_teacher_views.course_record, name='edit_course_record'),

    # 学习记录
    url(r'^study_record_list/(?P<course_record_id>\d+)/$',head_teacher_views.study_record_list,name='study_record_list')
]

mytitle8/crm/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager
from django.utils.translation import ugettext_lazy as _
from multiselectfield import MultiSelectField
from django.utils.safestring import mark_safe


# 课程
course_choices = (('Linux', 'Linux中高级'),
                  ('PythonFullStack', 'Python高级全栈开发'),
                  ('Go', 'Golang高级开发'),
                  )
# 课程类型选择
class_type_choices = (('fulltime', '脱产班',),
                      ('online', '网络班'),
                      ('weekend', '周末班',),)
# 什么资源来的
source_type = (('qq', "qq群"),
               ('referral', "内部转介绍"),
               ('website', "官方网站"),
               ('baidu_ads', "百度推广"),
               ('office_direct', "直接上门"),
               ('WoM', "口碑"),
               ('public_class', "公开课"),
               ('website_luffy', "路飞官网"),
               ('others', "其它"),)
# 注册状态
enroll_status_choices = (('signed', "已报名"),
                         ('unregistered', "未报名"),
                         ('studying', '学习中'),
                         ('paid_in_full', "学费已交齐"))
# 沟通状态
seek_status_choices = (('A', '近期无报名计划'), ('B', '1个月内报名'), ('C', '2周内报名'), ('D', '1周内报名'),
                       ('E', '定金'), ('F', '到班'), ('G', '全款'), ('H', '无效'),)
# 付款类型
pay_type_choices = (('deposit', "订金/报名费"),
                    ('tuition', "学费"),
                    ('transfer', "转班"),
                    ('dropout', "退学"),
                    )
# 出勤状态
attendance_choices = (('checked', "已签到"),
                      ('vacate', "请假"),
                      ('late', "迟到"),
                      ('absence', "缺勤"),
                      ('leave_early', "早退"),)
# 成绩
score_choices = ((100, 'A+'),
                 (90, 'A'),
                 (85, 'B+'),
                 (80, 'B'),
                 (70, 'B-'),
                 (60, 'C+'),
                 (50, 'C'),
                 (40, 'C-'),
                 (0, ' D'),
                 (-1, 'N/A'),
                 (-100, 'COPY'),
                 (-1000, 'FAIL'),)


# 创建客户表
class Customer(models.Model):
    """
    客户表
    """
    qq = models.CharField('QQ', max_length=64, unique=True, help_text='QQ号必须唯一')
    qq_name = models.CharField('QQ昵称', max_length=64, blank=True, null=True)
    name = models.CharField('姓名', max_length=32, blank=True, null=True, help_text='学员报名后，请改为真实姓名')
    sex_type = (('male', '男'), ('female', '女'))
    sex = models.CharField("性别", choices=sex_type, max_length=16, default='male', blank=True, null=True)
    birthday = models.DateField('出生日期', default=None, help_text="格式yyyy-mm-dd", blank=True, null=True)
    phone = models.BigIntegerField('手机号', blank=True, null=True)
    source = models.CharField('客户来源', max_length=64, choices=source_type, default='qq')
    # 外键关联
    introduce_from = models.ForeignKey('self', verbose_name="转介绍自学员", blank=True, null=True)
    course = MultiSelectField("咨询课程", choices=course_choices)
    class_type = models.CharField("班级类型", max_length=64, choices=class_type_choices, default='fulltime')
    customer_note = models.TextField("客户备注", blank=True, null=True, )
    status = models.CharField("状态", choices=enroll_status_choices, max_length=64, default="unregistered",
                              help_text="选择客户此时的状态")
    network_consult_note = models.TextField(blank=True, null=True, verbose_name='网络咨询师咨询内容')  # 详细名称
    date = models.DateTimeField("咨询日期", auto_now_add=True)
    last_consult_date = models.DateField("最后跟进日期", auto_now_add=True)
    next_date = models.DateField("预计再次跟进时间", blank=True, null=True)
    # 外键关联
    network_consultant = models.ForeignKey('UserProfile', blank=True, null=True, verbose_name='咨询师',
                                           related_name='network_consultant')  # 别名
    # 外键关联
    consultant = models.ForeignKey('UserProfile', verbose_name="销售", related_name='customers', blank=True, null=True, )
    # 多对多关联
    class_list = models.ManyToManyField('ClassList', verbose_name="已报班级", null=True, blank=True)

    class Meta:
        verbose_name = '客户'
        verbose_name_plural = '客户'

    def __str__(self):
        return '{}_{}'.format(self.name, self.qq)

    # 自定义类的方法
    def show_class_list(self):
        return '|'.join([str(i) for i in self.class_list.all()])

    # 展示状态
    def show_status(self):
        _status_color = {
            'signed': "blue",
            'unregistered': "red",
            'studying': 'orange',
            'paid_in_full': "green"
        }
        return mark_safe('<span style="background-color: {};color: white">{}</span>'.format(
            _status_color[self.status],
            self.get_status_display()
        ))


class Campuses(models.Model):
    """
    校区表
    """
    name = models.CharField(verbose_name='校区', max_length=64)
    address = models.CharField(verbose_name='详细地址', max_length=512, blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '校区表'
        verbose_name_plural = verbose_name


class ContractTemplate(models.Model):
    """
    合同模板表
    """
    name = models.CharField("合同名称", max_length=128, unique=True)  # 这些简写的是verbose_name='合同名称'
    content = models.TextField("合同内容")
    date = models.DateField(auto_now=True)


class ClassList(models.Model):
    """
    班级表
    """
    course = models.CharField("课程名称", max_length=64, choices=course_choices)
    semester = models.IntegerField("学期")
    # 外键关联
    campuses = models.ForeignKey('Campuses', verbose_name="校区")
    price = models.IntegerField("学费", default=10000)
    memo = models.CharField('说明', blank=True, null=True, max_length=100)
    start_date = models.DateField("开班日期")
    graduate_date = models.DateField("结业日期", blank=True, null=True)
    contract = models.ForeignKey('ContractTemplate', verbose_name="选择合同模版", blank=True, null=True)
    teachers = models.ManyToManyField('UserProfile', verbose_name="老师")
    class_type = models.CharField(choices=class_type_choices, max_length=64, verbose_name='班额及类型', blank=True,
                                  null=True)

    class Meta:
        unique_together = ("course", "semester", 'campuses')
        verbose_name = '班级表'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '{}-{}-{}'.format(self.get_course_display(), self.semester, self.campuses)


class ConsultRecord(models.Model):
    """
    跟进记录表
    """
    customer = models.ForeignKey('Customer', verbose_name="所咨询客户")
    note = models.TextField(verbose_name="跟进内容...")
    status = models.CharField("跟进状态", max_length=8, choices=seek_status_choices, help_text="选择客户此时的状态")
    consultant = models.ForeignKey("UserProfile", verbose_name="跟进人", related_name='records')
    date = models.DateTimeField("跟进日期", auto_now_add=True)
    delete_status = models.BooleanField(verbose_name='删除状态', default=False)


class Enrollment(models.Model):
    """
    报名表
    """

    why_us = models.TextField("为什么报名", max_length=1024, default=None, blank=True, null=True)
    your_expectation = models.TextField("学完想达到的具体期望", max_length=1024, blank=True, null=True)
    contract_agreed = models.BooleanField("我已认真阅读完培训协议并同意全部协议内容", default=False)
    contract_approved = models.BooleanField("审批通过", help_text="在审阅完学员的资料无误后勾选此项,合同即生效", default=False)
    enrolled_date = models.DateTimeField(auto_now_add=True, verbose_name="报名日期")
    memo = models.TextField('备注', blank=True, null=True)
    delete_status = models.BooleanField(verbose_name='删除状态', default=False)
    customer = models.ForeignKey('Customer', verbose_name='客户名称')
    school = models.ForeignKey('Campuses')
    enrolment_class = models.ForeignKey("ClassList", verbose_name="所报班级")

    class Meta:
        unique_together = ('enrolment_class', 'customer')


class PaymentRecord(models.Model):
    """
    缴费记录表
    """
    pay_type = models.CharField("费用类型", choices=pay_type_choices, max_length=64, default="deposit")
    paid_fee = models.IntegerField("费用数额", default=0)
    note = models.TextField("备注", blank=True, null=True)
    date = models.DateTimeField("交款日期", auto_now_add=True)
    course = models.CharField("课程名", choices=course_choices, max_length=64, blank=True, null=True, default='N/A')
    class_type = models.CharField("班级类型", choices=class_type_choices, max_length=64, blank=True, null=True,
                                  default='N/A')
    enrolment_class = models.ForeignKey('ClassList', verbose_name='所报班级', blank=True, null=True)
    customer = models.ForeignKey('Customer', verbose_name="客户")
    consultant = models.ForeignKey('UserProfile', verbose_name="销售")
    delete_status = models.BooleanField(verbose_name='删除状态', default=False)

    status_choices = (
        (1, '未审核'),
        (2, '已审核'),
    )
    status = models.IntegerField(verbose_name='审核', default=1, choices=status_choices)

    confirm_date = models.DateTimeField(verbose_name="确认日期", null=True, blank=True)
    confirm_user = models.ForeignKey(verbose_name="确认人", to='UserProfile', related_name='confirms', null=True,
                                     blank=True)


class CourseRecord(models.Model):
    """课程记录表"""
    day_num = models.IntegerField("节次", help_text="此处填写第几节课或第几天课程...,必须为数字")
    date = models.DateField(auto_now_add=True, verbose_name="上课日期")
    course_title = models.CharField('本节课程标题', max_length=64, blank=True, null=True)
    course_memo = models.TextField('本节课程内容', max_length=300, blank=True, null=True)
    has_homework = models.BooleanField(default=True, verbose_name="本节有作业")
    homework_title = models.CharField('本节作业标题', max_length=64, blank=True, null=True)
    homework_memo = models.TextField('作业描述', max_length=500, blank=True, null=True)
    scoring_point = models.TextField('得分点', max_length=300, blank=True, null=True)
    re_class = models.ForeignKey('ClassList', verbose_name="班级")
    teacher = models.ForeignKey('UserProfile', verbose_name="讲师")

    class Meta:
        unique_together = ('re_class', 'day_num')

    def show_name(self):

mytitle8/templates/add_customer.html
{% extends 'base.html' %}
{% block page-main %}
<h2 class="text-center">录入客户信息</h2>
            <form class="form-horizontal" action="" method="post" novalidate>
                {% csrf_token %}
                {% for field in form_obj %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}" class="col-sm-2 control-label">{{ field.label }}</label>
                        <div class="col-sm-10">
                            {{ field }}
                        </div>
                    </div>
                {% endfor %}
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-default">提交</button>
                    </div>
                </div>
            </form>
{% endblock %}

mytitle8/templates/base.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="https://v3.bootcss.com/favicon.ico">

    <title>客户展示页面</title>
    {% load static %}
    <!-- Bootstrap core CSS -->
    <link href="{% static 'bootstrap-3.3.7/css/bootstrap.css' %}" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{% static 'css/dashboard.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'font-awesome/css/font-awesome.css' %}">
    {% block page-css %}

    {% endblock %}
</head>
<body>
{% include 'nav.html' %}

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
            <ul class="nav nav-sidebar">
                <li><a href="/customer_list/">客户列表</a></li>
                <li><a href="/my_customer/">我的客户</a></li>
                <li><a href="{% url 'consult_record' 0 %}">沟通记录</a></li>
                <li><a href="{% url 'enrollment_list' 0 %}">查看报名表</a></li>
                <li><a href="/class_list/">班级列表</a></li>
            </ul>

        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            {% block page-main %}

            {% endblock %}
        </div>


    </div>
</div>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="{% static 'jquery.js' %}"></script>
<script src="{% static 'bootstrap-3.3.7/js/bootstrap.js' %}"></script>
{% block page-js %}

{% endblock %}
</body>
</html>

mytitle8/templates/class_list.html
{% extends 'base.html' %}

{% block page-main %}
    <h2 class="sub-header">班级列表</h2>
    <div class="col-md-12">
        <a href="/add_class/" class="btn btn-success btn-sm">添加</a>
        <div class="col-md-4 pull-right">
            <form action="" method="get" enctype="application/x-www-form-urlencoded">
                <div class="input-group">
                    <input type="text" name="query" class="form-control" placeholder="Search for...">
                    <span class="input-group-btn">
        <button class="btn btn-default" type="submit">搜呀</button>
      </span>
                </div><!-- /input-group -->
            </form>
        </div>
    </div>
    <form action="" method="post">
        {% csrf_token %}
        <div class="col-md-3" style="margin: 5px 0">
            <div class="input-group">
                <select class="form-control" name="action">
                    <option value="">---------</option>
                    <option value="to_public">变为公户</option>
                    <option value="to_private">变为私户</option>
                    <option value="delete">删除</option>
                </select>
                <div class="input-group-btn">
                    <button type="submit" class="btn btn-primary">提交</button>
                </div>
            </div>
        </div>
        <div class="col-md-12">
            <div class="table-responsive">
                <table class="table table-striped table-bordered">
                    <thead>
                    <tr>
                        <th style="width: 20px">选择</th>
                        <th style="width: 20px">#</th>
                        <th style="width: 80px">课程名称</th>
                        <th style="width: 80px">学期</th>
                        <th style="width: 60px">校区</th>
                        <th style="width: 80px">学费</th>
                        <th style="width: 90px">说明</th>
                        <th style="width: 120px">开班日期</th>
                        <th style="width: 60px">结业日期</th>
                        <th style="width: 60px">老师</th>
                        <th style="width: 60px">班级类型</th>
                        <th style="width: 20px!important;">操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for class in class_list %}
                        <tr>
                            <td><input type="checkbox" name="cid" value="{{ class.id }}"></td>
                            <td>{{ forloop.counter }}</td>
                            <td><a href="{% url 'course_record_list' class.id %}">{{ class.course }}</a></td>
                            <td>{{ class.semester }}</td>
                            <td>{{ class.campuses }}</td>
                            <td>{{ class.price }}</td>
                            <td>{{ class.memo }}</td>
                            <td>{{ class.start_date }}</td>
                            <td>{{ class.graduate_date }}</td>
                            <td>{{ class.teachers }}</td>
                            <td>{{ class.get_class_type_display }}</td>

                            <td><a href="/edit_class/"><i class="fa fa-edit" aria-hidden="true"></i></a></td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                <div>
                    {{ page_html|safe }}
                </div>
            </div>
        </div>

    </form>
{% endblock %}

mytitle8/templates/consult_record.html
{% extends 'base.html' %}

{% block page-main %}
    <div>
        <h2 class="text-center">{% if edit_id %}编辑沟通记录{% else %}添加沟通记录{% endif %}</h2>
        <form class="form-horizontal" action="" method="post" novalidate>
            {% csrf_token %}
            {% for field in form_obj %}
                <div class="form-group {% if  field.errors.0 %}has-error{% endif %}">
                    <label for="{{ field.id_for_label }}" class="col-sm-2 control-label">{{ field.label }}</label>
                    <div class="col-sm-10">
                        {{ field }}
                        <span class="help-block">{{ field.errors.0 }}</span>
                    </div>
                </div>
            {% endfor %}
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-default">提交</button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

mytitle8/templates/course_list.html
{% extends 'base.html' %}

{% block page-main %}
    <h2 class="sub-header">课程记录列表</h2>
    <div class="col-md-12">
        <a href="{% url 'add_course_record' class_id %}?{{ next_url }}" class="btn btn-success btn-sm">添加</a>
        <div class="col-md-4 pull-right">
            <form action="" method="get" enctype="application/x-www-form-urlencoded">
                <div class="input-group">
                    <input type="text" name="query" class="form-control" placeholder="Search for...">
                    <span class="input-group-btn">
        <button class="btn btn-default" type="submit">搜呀</button>
      </span>
                </div><!-- /input-group -->
            </form>
        </div>
    </div>
    <form action="" method="post">
        {% csrf_token %}
        <div class="col-md-3" style="margin: 5px 0">
            <div class="input-group">
                <select class="form-control" name="action">
                    <option value="">---------</option>
                    <option value="multi_init">初始化学习记录</option>
                    <option value="delete">删除</option>
                </select>
                <div class="input-group-btn">
                    <button type="submit" class="btn btn-primary">提交</button>
                </div>
            </div>
        </div>
        <div class="col-md-12">
            <div class="table-responsive">
                <table class="table table-striped table-bordered">
                    <thead>
                    <tr>
                        <th>选择</th>
                        <th>#</th>
                        <th>课程节次</th>
                        <th>课程标题</th>
                        <th>上课时间</th>
                        <th>作业</th>
                        <th>授课老师</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for course_record in course_record_list %}
                        <tr>
                            <td><input type="checkbox" name="cid" value="{{ course_record.id }}"></td>
                            <td>{{ forloop.counter }}</td>
                            <td><a href="{% url 'study_record_list' course_record.id %}">{{ course_record.show_name }}</a></td>
                            <td>{{ course_record.course_title }}</td>
                            <td>{{ course_record.date }}</td>
                            <td>{{ course_record.has_homework }}</td>
                            <td>{{ course_record.teacher.name }}</td>

                            <td><a href="{% url 'edit_course_record' course_record.id %}"><i class="fa fa-edit" aria-hidden="true"></i></a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                <div>
                    {{ page_html|safe }}
                </div>
            </div>
        </div>

    </form>
{% endblock %}

mytitle8/templates/customer.html
{% extends 'base.html' %}

{% block page-main %}
    <h2 class="text-center">{% if edit_id %}编辑客户信息{% else %}添加客户信息{% endif %}</h2>
    <form class="form-horizontal" action="" method="post" novalidate>
        {% csrf_token %}
        {% for field in form_obj %}
            <div class="form-group{% if field.errors.0 %}has-error{% endif %}">
                <label for="{{ field.id_for_label }}" class="col-sm-2 control-label">{{ field.label }}</label>
                <div class="col-sm-10">
                    {{ field }}
                    <span class="help-block">{{ field.errors.0 }}</span>
                </div>
            </div>
        {% endfor %}
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-default">提交</button>
            </div>
        </div>
    </form>

{% endblock %}

mytitle8/templates/edit_customer.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="https://v3.bootcss.com/favicon.ico">

    <title>客户修改页面</title>
    {% load static %}
    <!-- Bootstrap core CSS -->
    <link href="{% static 'bootstrap-3.3.7/css/bootstrap.css' %}" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{% static 'css/dashboard.css' %}" rel="stylesheet">

</head>

<body>

{% include 'nav.html' %}

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
            <ul class="nav nav-sidebar">
                <li class="active"><a href="/crm/customer_list/">客户列表</a>
                </li>
                <li><a href="https://v3.bootcss.com/examples/dashboard/#">Reports</a></li>
                <li><a href="https://v3.bootcss.com/examples/dashboard/#">Analytics</a></li>
                <li><a href="https://v3.bootcss.com/examples/dashboard/#">Export</a></li>
            </ul>

        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">

            <form class="form-horizontal" action="" method="post" novalidate>
                {% csrf_token %}
                {% for field in form_obj %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}" class="col-sm-2 control-label">{{ field.label }}</label>
                        <div class="col-sm-10">
                            {{ field }}
                        </div>
                    </div>
                {% endfor %}
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-default">提交</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
</div>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="{% static 'jquery.js' %}"></script>
<script src="{% static 'bootstrap-3.3.7/js/bootstrap.js' %}"></script>
</body>
</html>

mytitle8/templates/encollment_list.html
{% extends 'base.html' %}

{% block page-main %}
    <h2 class="sub-header">报名表</h2>
    <div class="col-md-12">
        <div class="col-md-4 pull-right">
            <form action="" method="get" enctype="application/x-www-form-urlencoded">
                <div class="input-group">
                    <input type="text" name="query" class="form-control" placeholder="Search for...">
                    <span class="input-group-btn">
        <button class="btn btn-default" type="submit">搜呀</button>
      </span>
                </div><!-- /input-group -->
            </form>
        </div>
    </div>
    <form action="" method="post">
        {% csrf_token %}
        <div class="col-md-3" style="margin: 5px 0">
            <div class="input-group">
                <select class="form-control" name="action">
                    <option value="">---------</option>
                    <option value="to_public">变为公户</option>
                    <option value="to_private">变为私户</option>
                    <option value="delete">删除</option>
                </select>
                <div class="input-group-btn">
                    <button type="submit" class="btn btn-primary">提交</button>
                </div>
            </div>
        </div>
        <div class="col-md-12">
            <div class="table-responsive">
                <table class="table table-striped table-bordered">
                    <thead>
                    <tr>
                        <th style="width: 20px">选择</th>
                        <th style="width: 20px">#</th>
                        <th style="width: 80px">客户</th>
                        <th style="width: 80px">课程</th>
                        <th style="width: 80px">校区</th>
                        <th style="width: 80px">报名原因</th>
                        <th style="width: 80px">期望</th>
                        <th style="width: 80px">是否同意协议</th>
                        <th style="width: 60px">报名时间</th>
                        <th style="width: 80px">备注</th>
                        <th style="width: 20px!important;">操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for enrollment in enrollment_list %}
                        <tr>
                            <td><input type="checkbox" name="cid" value="{{ enrollment.id }}"></td>
                            <td>{{ forloop.counter }}</td>
                            <td>{{ enrollment.customer.name }}</td>
                            <td>{{ enrollment.enrolment_class }}</td>
                            <td>{{ enrollment.school }}</td>
                            <td>{{ enrollment.why_us }}</td>
                            <td>{{ enrollment.your_expectation }}</td>
                            <td>{{ enrollment.contract_agreed }}</td>
                            <td>{{ enrollment.enrolled_date }}</td>
                            <td>{{ enrollment.memo }}</td>
                            <td><a href="/edit_enrollment/?enrollment_id={{ enrollment.id }}"><i class="fa fa-edit"
                                                                                   aria-hidden="true"></i></a></td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                <div>
                    {{ page_html|safe }}
                </div>
            </div>
        </div>

    </form>
{% endblock %}

mytitle8/templates/enrollment.html
{% extends 'base.html' %}

{% block page-main %}
    <div>
        <h2 class="text-center">{% if edit_id %}编辑报名表 {% else %}添加报名表{% endif %}</h2>
        <form class="form-horizontal" action="" method="post" novalidate>
            {% csrf_token %}
            {% for field in form_obj %}
                <div class="form-group {% if  field.errors.0 %}has-error{% endif %}">
                    <label for="{{ field.id_for_label }}" class="col-sm-2 control-label">{{ field.label }}</label>
                    <div class="col-sm-10">
                        {{ field }}
                        <span class="help-block">{{ field.errors.0 }}</span>
                    </div>
                </div>
            {% endfor %}
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-default">提交</button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

{% block page-js %}
    {% load static %}
    <script src="{% static 'jquery.js' %}"></script>
    <script>
    $(document).ready(function () {     //ready等DOM树加载完毕后就能执行,选择了校区就立马加载里面的班级
        $('#id_school').on('change',function () {
            var sId = $(this).val();
            // 获取到选中的校区id
            // 发AJAX到后端去除当前校区下面所有的课程
            $.ajax({
                url:'/ajax_class/',
                type:'get',
                data:{'sid':sId},
                success:function (res) {
                    console.log(res);
                    var $classSelect = $('#id_enrolment_class');
                    $classSelect.text('');
                    $classSelect.append('<option value="">-------</option>');
                    $.each(res.data,function (k,v) {
                        console.log(k,v);
                        var opEle = document.createElement('option');
                        $(opEle).text(v.name).attr('value',v.id);
                        $classSelect.append(opEle);
                    })
                }
            })
        })
    })
    </script>
{% endblock %}